### ISSUE TITLE
add explicit license

### ISSUE THREAD

**Issue by zabbal** [rrthomas/beetle#1]
Would be nice to add explicit license instead of the symlink to ancient automake version. Also it would clarify confusion: is it GPLv3? or v2? or v2+? The automake has upgraded it's license which is a great thing but I'm not sure if it's applicable to this project as well.

**Comment by rrthomas** [comment]
This is already clear in the README: "The package is distributed under the GNU Public License version 3, or, at your option, any later version."

Apologies for the symlink, now fixed.
