### ISSUE TITLE
libbeetle should depend on c-decls.h

### ISSUE THREAD

**Issue by apt1002** [rrthomas/beetle#14]
If I edit the file `mijit-beetle/c-decls.h` then rebuild beetle, the build is incomplete. Please consider adding an extra dependency to the Makefile.

**Comment by rrthomas** [comment]
Fixed.

**Comment by rrthomas** [comment]
Unfixed. I'm not convinced that one project ought to be depending on internals of a sub-project. It occurred to me that the C compiler dependency generation should catch this, as it does for system headers. Indeed, in a build of mine, it does: `src/.deps/step.Plo` gives `step.lo` a dependency on `../mijit-beetle/c-decls.h`, and touching that file causes `step.c` to be recompiled. So, I assert this already works OK.

**Comment by apt1002** [comment]
Okay, I have nothing further to add.
