### ISSUE TITLE
Use mijit-beetle when available

### ISSUE THREAD

**Issue by apt1002** [rrthomas/beetle#16]
Surprisingly, although it does no optimization, mijit-beetle already makes beetle go faster. Time to run:

```
$BEETLE pforth make.fs
```

| Beetle 2.1.1 | Beetle 'master' branch | Beetle 'mijit' branch |
| ---------------- | --------------- | ----------------- |
| 6.84s | 6.68s | 4.71s |
| -0% | -2% | -31% |

**Comment by rrthomas** [comment]
Done in version 3, as an option: mijit-beetle is not faster once some basic C inlining is done.
