### ISSUE TITLE
(+LOOP) should use the carry or overflow flag, not the sign bit

### ISSUE THREAD

**Issue by apt1002** [rrthomas/beetle#9]
> Add [increment] to [index] ; if [index] thereby crosses the [limit] - 1 to [limit] boundary, [...]

It's not clear what this means unless we know whether to interpret `increment` as signed or unsigned. For example, if `increment` is `1<<31`, it could be interpreted as positive (unsigned) or negative (signed). Suppose `index` and `limit` are, say `5` and `0` respectively. If `increment` is interpreted as positive, then it does not cross the boundary, but if negative it does.

I *think* the fix is to specify that `increment` is always signed. It is not necessary to specify whether `index` and `limit` are signed or unsigned; just use cyclic arithmetic.

**Comment by apt1002** [comment]
The [GForth implementation](http://git.savannah.gnu.org/cgit/gforth.git/tree/prim#n373) implements it like this:
```
Cell olddiff = n1-nlimit;
n2=n1+n;	
if (((olddiff^(olddiff+n))    /* the limit is not crossed */
     &(olddiff^n))	       /* OR it is a wrap-around effect */
    >=0) { /* & is used to avoid having two branches for gforth-native */
{ ... }
```
I can understand this by separately deoptimising the `n>=0` and `n<0` cases:
```
Cell olddiff = n1-nlimit;
n2=n1+n;	
Cell newdiff = n2-nlimit;
if ((n >= 0) ? (
    olddiff < 0 && newdiff >=0
) : (
    olddiff >=0 && newdiff < 0
)) { ... }
```
In other words, we exit the loop if `olddiff` and `newdiff` have opposite sign and `olddiff` and `n` have opposite sign.

**Comment by rrthomas** [comment]
Submit a patch to gforth based on the above, which replaces the comment "check this thoroughly", and removes the comment about defunct `gforth-native`.
